// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjON71pFWyJEEdiyOXdrRZl4TskUvuJzw',
    appId: '1:582225428801:web:7f79785e8f12d451fde1c0',
    messagingSenderId: '582225428801',
    projectId: 'flutter-test-169dd',
    authDomain: 'flutter-test-169dd.firebaseapp.com',
    storageBucket: 'flutter-test-169dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIK5Ye2D-hnTsQ--d30TmHF431pz1c6l8',
    appId: '1:582225428801:android:4e9523c2541a7e07fde1c0',
    messagingSenderId: '582225428801',
    projectId: 'flutter-test-169dd',
    storageBucket: 'flutter-test-169dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv4wp4OHYBp5FlDW1kPv-054dRAt6F3VE',
    appId: '1:582225428801:ios:c92d221ee1339f3cfde1c0',
    messagingSenderId: '582225428801',
    projectId: 'flutter-test-169dd',
    storageBucket: 'flutter-test-169dd.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv4wp4OHYBp5FlDW1kPv-054dRAt6F3VE',
    appId: '1:582225428801:ios:c92d221ee1339f3cfde1c0',
    messagingSenderId: '582225428801',
    projectId: 'flutter-test-169dd',
    storageBucket: 'flutter-test-169dd.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjON71pFWyJEEdiyOXdrRZl4TskUvuJzw',
    appId: '1:582225428801:web:7e0c425b647828cbfde1c0',
    messagingSenderId: '582225428801',
    projectId: 'flutter-test-169dd',
    authDomain: 'flutter-test-169dd.firebaseapp.com',
    storageBucket: 'flutter-test-169dd.firebasestorage.app',
  );

}